services:

  portredirector:
    #image: ${DOCKER_REGISTRY-}api
    container_name: portredirector
    build:
      context: ./src
      dockerfile: ./Dockerfile
    volumes:
      - "./appsettings.json:/app/appsettings.json"
    ports:
      - "12345-12350:12345-12350"
